/**
 * AnalysisReportPage.jsx
 * Descriptive + Diagnostic + Predictive DSS report panels.
 * Predictive panel uses pathway-indexed cycling indices (MCI, SCI, ASI)
 * computed by the backend from FAPROTAX-mapped functional abundances.
 */

import React, { useState, useEffect, useRef, useCallback } from 'react'

// ── PDF Generation ────────────────────────────────────────────────────────────

async function generateReportPdf(report, { reportType, samples }) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const PW = 210, PH = 297, ML = 22, MR = 22, TW = 210 - 22 - 22
  let y = 22, pageNum = 1

  const footer = () => {
    doc.setFont('helvetica', 'normal').setFontSize(7.5).setTextColor(160, 150, 140)
    doc.text('Sedimentra Genomic Intelligence System — Confidential Diagnostic Report', ML, PH - 10)
    doc.text(`Page ${pageNum}`, PW - MR, PH - 10, { align: 'right' })
  }
  const addPage = () => { footer(); doc.addPage(); pageNum++; y = 22 }
  const chk = (n = 16) => { if (y + n > PH - 18) addPage() }

  const h2 = (text, rgb = [29, 90, 60]) => {
    chk(14); doc.setFont('helvetica', 'bold').setFontSize(10).setTextColor(...rgb)
    doc.text(text.toUpperCase(), ML, y); y += 5
    doc.setDrawColor(...rgb).setLineWidth(0.4).line(ML, y, PW - MR, y); y += 5
  }
  const h3 = (text) => {
    chk(10); doc.setFont('helvetica', 'bold').setFontSize(9.5).setTextColor(50, 50, 50)
    doc.text(text, ML, y); y += 6
  }
  const kv = (key, val, indent = 0) => {
    chk(7); doc.setFont('helvetica', 'bold').setFontSize(8.5).setTextColor(110, 100, 90)
    doc.text(key, ML + indent, y)
    doc.setFont('helvetica', 'normal').setTextColor(40, 40, 40)
    doc.text(String(val ?? '—'), ML + indent + 56, y); y += 5.8
  }
  const para = (text, indent = 0) => {
    chk(10); doc.setFont('helvetica', 'normal').setFontSize(8.5).setTextColor(60, 60, 60)
    const lines = doc.splitTextToSize(text, TW - indent)
    doc.text(lines, ML + indent, y); y += lines.length * 5
  }
  const gap = (n = 6) => { y += n }

  // ── Cover Page ──────────────────────────────────────────────────────────────
  doc.setFillColor(29, 158, 117).rect(0, 0, 6, PH, 'F')
  y = 52
  doc.setFont('helvetica', 'bold').setFontSize(26).setTextColor(17, 17, 17)
  doc.text('Sedimentra', ML, y); y += 10
  doc.setFont('helvetica', 'normal').setFontSize(11).setTextColor(100, 90, 80)
  doc.text('Genomic Intelligence System — Ecological Report', ML, y); y += 20
  doc.setDrawColor(220, 216, 208).setLineWidth(0.4).line(ML, y, PW - MR, y); y += 14

  const typeLabel = { descriptive: 'Descriptive', diagnostic: 'Diagnostic', both: 'Descriptive + Diagnostic' }[reportType]
  kv('Report Type:', typeLabel)
  kv('Samples Included:', samples.length)
  kv('Sample IDs:', samples.join(', '))
  kv('Generated:', new Date().toLocaleString('en-PH', { timeZone: 'Asia/Manila', dateStyle: 'long', timeStyle: 'short' }))
  gap(12)
  doc.setDrawColor(220, 216, 208).setLineWidth(0.3).line(ML, y, PW - MR, y); y += 12
  doc.setFont('helvetica', 'normal').setFontSize(8).setTextColor(130, 120, 110)
  const disc = 'This report is generated by the Sedimentra Genomic Intelligence System. All functional inferences are based on FAPROTAX literature assignments and represent ecological potential, not confirmed metabolic activity. Percentile-calibrated risk indices are dataset-relative. This document is intended as a diagnostic aid for the Department of Environment and Natural Resources (DENR) Region VIII and should be interpreted alongside physical and chemical sediment analyses.'
  const discLines = doc.splitTextToSize(disc, TW)
  doc.text(discLines, ML, y)
  footer()

  // ── Per-Sample Sections ─────────────────────────────────────────────────────
  const incDesc = reportType !== 'diagnostic'
  const incDiag = reportType !== 'descriptive'
  const RISK_RGB = { Low: [29, 158, 117], Moderate: [186, 117, 23], High: [216, 90, 48], Critical: [226, 75, 74] }
  const STRESS_LABELS = ['Stable', 'Mildly Disturbed', 'Moderately Disturbed', 'Heavily Disturbed']

  for (let si = 0; si < samples.length; si++) {
    const sid = samples[si]
    const dd = report.descriptive?.find(d => d.sample_id === sid)
    const dg = report.diagnostic?.find(d => d.sample_id === sid)
    addPage()

    // Sample header banner
    doc.setFillColor(248, 247, 244).rect(ML - 4, y - 6, TW + 8, 14, 'F')
    doc.setFont('helvetica', 'bold').setFontSize(13).setTextColor(17, 17, 17)
    doc.text(`Sample: ${sid}`, ML, y)
    doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(147, 133, 117)
    doc.text(`${si + 1} of ${samples.length}`, PW - MR, y, { align: 'right' })
    y += 14

    // ── Descriptive ───────────────────────────────────────────────────────────
    if (incDesc && dd) {
      h2('Microbial Community Profile — Descriptive Analysis', [29, 90, 60])
      kv('Shannon Entropy (H\u2019):', dd.shannon_entropy?.toFixed(3))
      kv('Observed Genera:', dd.observed_genera)
      kv('Diversity Status:', dd.diversity_status)
      kv('Dominant Genus:', dd.dominant_genus || '—')
      kv('Dominant Abundance:', dd.dominant_abundance != null ? `${(dd.dominant_abundance * 100).toFixed(1)}%` : '—')
      gap(5)

      h3('Top 10 Genera — Relative Abundance')
      const cW = [TW * 0.42, TW * 0.20, TW * 0.38]
      const cX = [ML, ML + cW[0], ML + cW[0] + cW[1]]
      chk(8); doc.setFillColor(240, 237, 232).rect(ML, y - 4, TW, 7, 'F')
      doc.setFont('helvetica', 'bold').setFontSize(7.5).setTextColor(100, 90, 80)
      doc.text('Genus', cX[0] + 2, y)
      doc.text('Rel. Abundance', cX[1] + 2, y)
      doc.text('FAPROTAX Functions', cX[2] + 2, y)
      y += 6.5
      dd.top10?.forEach((g, idx) => {
        chk(7)
        if (idx % 2 === 0) doc.setFillColor(252, 251, 249).rect(ML, y - 4, TW, 6.5, 'F')
        doc.setFont('helvetica', 'italic').setFontSize(8).setTextColor(30, 30, 30)
        doc.text(g.genus || '—', cX[0] + 2, y)
        doc.setFont('helvetica', 'normal').setTextColor(80, 80, 80)
        doc.text(`${(g.abundance * 100).toFixed(2)}%`, cX[1] + 2, y)
        const ft = g.functions?.length > 0 ? `${g.functions.length} function${g.functions.length > 1 ? 's' : ''}` : 'Unclassified'
        doc.setTextColor(100, 90, 80); doc.text(ft, cX[2] + 2, y); y += 6.5
      })
      gap(10)
    }

    // ── Diagnostic ────────────────────────────────────────────────────────────
    if (incDiag && dg) {
      h2('Ecological Disturbance Assessment — Diagnostic Analysis', [56, 90, 180])
      kv('Stress Classification:', STRESS_LABELS[dg.stress_level] || '—')
      kv('Flags Triggered:', `${dg.flags?.length || 0}  (${dg.critical_count || 0} critical · ${dg.warning_count || 0} warning)`)
      if (dg.confidence) kv('Confidence Level:', `${dg.confidence.level}  (${Math.round(dg.confidence.score * 100)}%)`)
      gap(4)

      if (dg.flags?.length > 0) {
        h3('Flagged Genera')
        const SEV_RGB = { critical: [226, 75, 74], warning: [186, 117, 23], info: [55, 138, 221] }
        dg.flags.forEach(f => {
          chk(22)
          const c = SEV_RGB[f.severity] || SEV_RGB.info
          doc.setFont('helvetica', 'bold').setFontSize(9).setTextColor(17, 17, 17)
          doc.text(f.genus, ML + 2, y)
          doc.setFont('helvetica', 'bold').setFontSize(7.5).setTextColor(...c)
          doc.text(f.severity.toUpperCase(), ML + 68, y); y += 5.5
          doc.setFont('helvetica', 'normal').setFontSize(8).setTextColor(80, 70, 60)
          doc.text(`Abundance: ${(f.abundance * 100).toFixed(2)}%  |  ${f.threshold}  |  ${f.direction}`, ML + 4, y); y += 5.5
          para(f.interpretation, 4)
          doc.setDrawColor(230, 225, 218).setLineWidth(0.2).line(ML, y, PW - MR, y); y += 5
        })
      } else { para('No ecological stress flags triggered. Community appears within expected bounds.') }
      gap(4)

      if (dg.cycling_indices) {
        const ci = dg.cycling_indices
        h3('Biogeochemical Cycling Risk Indices')
        const ri = (label, val, risk, ratioLbl) => {
          chk(16); const rgb = RISK_RGB[risk] || RISK_RGB.Low
          doc.setFont('helvetica', 'bold').setFontSize(9).setTextColor(50, 50, 50)
          doc.text(label, ML + 2, y)
          doc.setFont('helvetica', 'bold').setFontSize(9).setTextColor(...rgb)
          doc.text(`${val?.toFixed(3)}  —  ${risk}`, ML + 82, y); y += 5.5
          if (ratioLbl) { doc.setFont('helvetica', 'normal').setFontSize(8).setTextColor(100,90,80); doc.text(ratioLbl, ML + 6, y); y += 5 }
        }
        ri('Methane Cycle Index (MCI)', ci.mci, ci.mci_risk, ci.ch4_ratio_label)
        ri('Sulfur Cycle Index (SCI)', ci.sci, ci.sci_risk, ci.s_ratio_label)
        chk(10)
        doc.setFont('helvetica', 'bold').setFontSize(9).setTextColor(50, 50, 50)
        doc.text('Anoxic Support Index (ASI)', ML + 2, y)
        doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(90,80,70)
        doc.text(`${ci.asi?.toFixed(4)}  —  ${ci.asi_level}`, ML + 82, y); y += 8
      }

      if (dg.trajectory) {
        const tr = dg.trajectory
        h3('Functional Risk Trajectory')
        kv('Direction:', tr.direction); kv('Regression Slope:', tr.slope?.toFixed(4))
        kv('Samples Analysed:', tr.sample_count); gap(3); para(tr.projected_risk_state, 2); gap(6)
      }

      if (dg.recommendations?.length > 0) {
        h3('Management Recommendations')
        dg.recommendations.forEach(rec => {
          chk(30)
          doc.setFont('helvetica', 'bold').setFontSize(9).setTextColor(17, 17, 17)
          doc.text(rec.priority, ML + 2, y)
          doc.setFont('helvetica', 'normal').setFontSize(8.5).setTextColor(85, 85, 85)
          doc.text(`  ${rec.pathway}  ·  ${rec.trigger_index}`, ML + 58, y); y += 6
          doc.setFont('helvetica', 'bold').setFontSize(8.5).setTextColor(50, 50, 50)
          doc.text('Observation:', ML + 4, y); y += 5; para(rec.observation, 6)
          doc.setFont('helvetica', 'bold').setFontSize(8.5).setTextColor(50, 50, 50)
          doc.text('Action:', ML + 4, y); y += 5; para(rec.action, 6)
          doc.setDrawColor(220, 216, 208).setLineWidth(0.2).line(ML, y, PW - MR, y); y += 6
        })
      }

      if (dg.confidence) {
        gap(4); h3('Confidence Score Breakdown')
        const conf = dg.confidence
        const w = conf.weights || {}
        ;[
          ['FAPROTAX Functional Coverage', conf.functional_coverage, w.coverage || 0.40],
          ['Shannon Diversity Component',  conf.diversity_component,  w.diversity || 0.20],
          ['Sequencing Depth Component',   conf.depth_component,      w.depth    || 0.20],
          ['Cross-Sample Consistency',     conf.cross_sample_consistency, w.consistency || 0.20],
        ].forEach(([lbl, val, wt]) => kv(`${lbl}:`, `${(val * 100).toFixed(0)}%  ×  weight ${(wt * 100).toFixed(0)}%`, 2))
        kv('Composite Score:', `${Math.round(conf.score * 100)}%  —  ${conf.level}`)
        conf.caveats?.forEach(c => para(`• ${c}`, 4))
      }
    }
  }

  footer()
  doc.save(`sedimentra-${reportType}-${new Date().toISOString().slice(0, 10)}.pdf`)
}

// ── Export Modal ──────────────────────────────────────────────────────────────

function ExportModal({ report, onClose }) {
  const [reportType, setReportType] = useState('both')
  const [sampleMode, setSampleMode] = useState('all')
  const [selectedSamples, setSelectedSamples] = useState([])
  const [exporting, setExporting] = useState(false)
  const [err, setErr] = useState(null)

  const allSamples = [...new Set([
    ...(report?.descriptive?.map(d => d.sample_id) || []),
    ...(report?.diagnostic?.map(d => d.sample_id) || []),
  ])]

  const toggleSample = useCallback(id =>
    setSelectedSamples(prev => prev.includes(id) ? prev.filter(s => s !== id) : [...prev, id]), [])

  const canExport = sampleMode === 'all' || selectedSamples.length > 0

  const handleExport = async () => {
    setErr(null); setExporting(true)
    try {
      await generateReportPdf(report, { reportType, samples: sampleMode === 'all' ? allSamples : selectedSamples })
      onClose()
    } catch (e) { setErr('PDF generation failed: ' + e.message) }
    finally { setExporting(false) }
  }

  const TYPES = [
    { value: 'descriptive', label: 'Descriptive', desc: 'Community profile & taxa' },
    { value: 'diagnostic',  label: 'Diagnostic',  desc: 'Stress flags & risk indices' },
    { value: 'both',        label: 'Both',         desc: 'Full combined report' },
  ]

  return (
    <div
      onClick={e => e.target === e.currentTarget && onClose()}
      style={{ position: 'fixed', inset: 0, zIndex: 1000, background: 'rgba(20,18,15,0.48)', display: 'flex', alignItems: 'center', justifyContent: 'center', backdropFilter: 'blur(4px)' }}
    >
      <div style={{ background: '#fff', borderRadius: 16, padding: '28px 32px', width: 468, maxWidth: '94vw', boxShadow: '0 12px 48px rgba(0,0,0,0.18)', fontFamily: 'Instrument Sans, sans-serif' }}>

        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 24 }}>
          <div>
            <div style={{ fontSize: 17, fontWeight: 700, color: '#111' }}>Export Report</div>
            <div style={{ fontSize: 12, color: '#938575', marginTop: 3 }}>Download as a formatted PDF file</div>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: 22, color: '#B0A898', lineHeight: 1, padding: '0 2px' }}>×</button>
        </div>

        {/* Report Type */}
        <div style={{ marginBottom: 22 }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: '#938575', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 10 }}>Report Type</div>
          <div style={{ display: 'flex', gap: 8 }}>
            {TYPES.map(({ value, label, desc }) => (
              <button
                key={value} onClick={() => setReportType(value)}
                style={{ flex: 1, padding: '10px 6px', borderRadius: 10, cursor: 'pointer', textAlign: 'center', border: reportType === value ? '1.5px solid #938575' : '1px solid #E0DCD4', background: reportType === value ? '#F9F7F5' : '#FAFAF8', transition: 'all .14s' }}
              >
                <div style={{ fontSize: 13, fontWeight: 700, color: reportType === value ? '#593E32' : '#444', marginBottom: 2 }}>{label}</div>
                <div style={{ fontSize: 10.5, color: '#938575' }}>{desc}</div>
              </button>
            ))}
          </div>
        </div>

        {/* Sample Selection */}
        <div style={{ marginBottom: 22 }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: '#938575', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 10 }}>Samples</div>
          <div style={{ display: 'flex', gap: 8, marginBottom: 10 }}>
            {[{ value: 'all', label: `All samples (${allSamples.length})` }, { value: 'selected', label: 'Choose samples' }].map(({ value, label }) => (
              <button
                key={value} onClick={() => setSampleMode(value)}
                style={{ flex: 1, padding: '8px 10px', borderRadius: 8, cursor: 'pointer', fontSize: 12, fontWeight: 600, border: sampleMode === value ? '1.5px solid #938575' : '1px solid #E0DCD4', background: sampleMode === value ? '#F9F7F5' : '#FAFAF8', color: sampleMode === value ? '#593E32' : '#666', transition: 'all .14s' }}
              >{label}</button>
            ))}
          </div>

          {sampleMode === 'selected' && (
            <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', padding: '10px 12px', background: '#F8F7F4', borderRadius: 8, minHeight: 44 }}>
              {allSamples.map(id => {
                const active = selectedSamples.includes(id)
                return (
                  <button key={id} onClick={() => toggleSample(id)} style={{ padding: '4px 12px', fontSize: 12, border: '0.5px solid ' + (active ? '#938575' : '#D4D0C8'), borderRadius: 20, cursor: 'pointer', background: active ? '#938575' : '#fff', color: active ? '#fff' : '#938575', fontFamily: 'Instrument Sans', fontWeight: active ? 600 : 400, transition: 'all .12s' }}>
                    {id}
                  </button>
                )
              })}
              {allSamples.length === 0 && <span style={{ fontSize: 12, color: '#938575' }}>No samples found</span>}
            </div>
          )}
          {sampleMode === 'selected' && selectedSamples.length === 0 && (
            <div style={{ fontSize: 11, color: '#D85A30', marginTop: 6 }}>Select at least one sample to export.</div>
          )}
        </div>

        {err && <div style={{ fontSize: 12, color: '#D85A30', background: '#FAECE7', borderRadius: 6, padding: '8px 12px', marginBottom: 14 }}>{err}</div>}

        <div style={{ borderTop: '0.5px solid #E8E4DC', marginBottom: 18 }} />

        {/* Actions */}
        <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end' }}>
          <button onClick={onClose} style={{ padding: '9px 20px', borderRadius: 8, border: '0.5px solid #D4D0C8', background: '#fff', color: '#666', fontSize: 13, fontWeight: 500, cursor: 'pointer', fontFamily: 'Instrument Sans' }}>
            Cancel
          </button>
          <button
            id="confirm-export-pdf-btn"
            onClick={handleExport} disabled={!canExport || exporting}
            style={{ padding: '9px 22px', borderRadius: 8, border: 'none', background: canExport && !exporting ? '#938575' : '#D4D0C8', color: '#fff', fontSize: 13, fontWeight: 600, cursor: canExport && !exporting ? 'pointer' : 'not-allowed', fontFamily: 'Instrument Sans', transition: 'background .15s', display: 'flex', alignItems: 'center', gap: 8 }}
          >
            {exporting ? '⏳ Generating…' : '↓ Export as PDF'}
          </button>
        </div>

      </div>
    </div>
  )
}
import { useLocation, useNavigate, useParams } from 'react-router-dom'
import { ingestApi } from '../api/client'

// ── Design tokens ─────────────────────────────────────────────────────────────

const COLORS = [
  '#1D9E75','#378ADD','#BA7517','#D85A30',
  '#3C3489','#0F6E56','#993C1D','#185FA5','#3B6D11','#A32D2D',
]

const STRESS_BADGE = {
  0: { label: 'Stable',               bg: '#E1F5EE', color: '#085041' },
  1: { label: 'Mildly Disturbed',     bg: '#FAEEDA', color: '#412402' },
  2: { label: 'Moderately Disturbed', bg: '#FAECE7', color: '#D85A30' },
  3: { label: 'Heavily Disturbed',    bg: '#FCEBEB', color: '#501313' },
}

const DIV_BADGE = {
  Low:    { bg: '#FCEBEB', color: '#501313' },
  Normal: { bg: '#E1F5EE', color: '#085041' },
  High:   { bg: '#E6F1FB', color: '#042C53' },
}

const SEV_BADGE = {
  critical: { bg: '#E24B4A', color: '#fff' },
  warning:  { bg: '#BA7517', color: '#fff' },
  info:     { bg: '#378ADD', color: '#fff' },
}

const FLAG_BG = {
  critical: { background: '#FCEBEB' },
  warning:  { background: '#FAEEDA' },
  info:     { background: '#E6F1FB' },
}

const RISK_COLORS = {
  Low:      { bg: '#E1F5EE', color: '#085041', bar: '#1D9E75' },
  Moderate: { bg: '#FAEEDA', color: '#7A4700', bar: '#BA7517' },
  High:     { bg: '#FAECE7', color: '#7A2200', bar: '#D85A30' },
  Critical: { bg: '#FCEBEB', color: '#501313', bar: '#E24B4A' },
}

const PRIORITY_STYLE = {
  'P1 — Immediate Action': { border: '#E24B4A', bg: '#FFFAFA', badge: { bg: '#E24B4A', color: '#fff' } },
  'P2 — Short-term Action': { border: '#BA7517', bg: '#FFFDF7', badge: { bg: '#BA7517', color: '#fff' } },
  'P3 — Monitor':           { border: '#378ADD', bg: '#F6FAFE', badge: { bg: '#378ADD', color: '#fff' } },
}

const CONF_STYLE = {
  High:     { dot: '#1D9E75', text: '#085041' },
  Moderate: { dot: '#BA7517', text: '#7A4700' },
  Low:      { dot: '#E24B4A', text: '#501313' },
}

// ── Utility ───────────────────────────────────────────────────────────────────

function pct(v, max = 1) { return Math.min(100, (v / max) * 100).toFixed(1) }

// ── Shared sub-components ────────────────────────────────────────────────────

function MetricCard({ label, value, sub }) {
  return (
    <div style={{ background: '#F8F7F4', borderRadius: 8, padding: '12px 14px', flex: 1, minWidth: 120 }}>
      <div style={{ fontSize: 11, color: '#938575', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 4 }}>{label}</div>
      <div style={{ fontSize: 22, fontWeight: 600, color: '#111', lineHeight: 1.2 }}>{value}</div>
      {sub && <div style={{ fontSize: 11, color: '#938575', marginTop: 2 }}>{sub}</div>}
    </div>
  )
}

function Badge({ bg, color, children, size = 12 }) {
  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', padding: '3px 10px', borderRadius: 20, fontSize: size, fontWeight: 600, background: bg, color }}>
      {children}
    </span>
  )
}

function SampleChips({ samples, active, onSelect }) {
  return (
    <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginBottom: 16 }}>
      {samples.map((s, i) => (
        <button key={s.sample_id} onClick={() => onSelect(i)} style={{
          padding: '5px 12px', fontSize: 12,
          border: '0.5px solid ' + (active === i ? '#1D9E75' : '#D4D0C8'),
          borderRadius: 20, cursor: 'pointer',
          background: active === i ? '#1D9E75' : '#fff',
          color: active === i ? '#fff' : '#938575',
          fontFamily: 'Instrument Sans', fontWeight: active === i ? 600 : 400,
          transition: 'all .12s',
        }}>
          {s.sample_id}
        </button>
      ))}
    </div>
  )
}

function ConfidenceBadge({ confidence }) {
  if (!confidence) return null
  const s = CONF_STYLE[confidence.level] || CONF_STYLE.Moderate
  const scorePct = confidence.score !== undefined ? Math.round(confidence.score * 100) : null
  return (
    <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, background: '#F8F7F4', borderRadius: 20, padding: '4px 12px', fontSize: 12 }}>
      <span style={{ width: 8, height: 8, borderRadius: '50%', background: s.dot, display: 'inline-block' }} />
      <span style={{ color: s.text, fontWeight: 600 }}>{confidence.level} Confidence</span>
      {scorePct !== null && <span style={{ color: '#938575' }}>({scorePct}%)</span>}
    </div>
  )
}

// ── Bar Chart ────────────────────────────────────────────────────────────────

function GenusBarChart({ top10 }) {
  const canvasRef = useRef(null)
  const chartRef  = useRef(null)
  useEffect(() => {
    if (!canvasRef.current || !window.Chart) return
    if (chartRef.current) chartRef.current.destroy()
    chartRef.current = new window.Chart(canvasRef.current, {
      type: 'bar',
      data: {
        labels: top10.map(g => g.genus),
        datasets: [{ label: 'Relative abundance (%)', data: top10.map(g => parseFloat((g.abundance * 100).toFixed(2))), backgroundColor: COLORS.slice(0, top10.length), borderRadius: 4, borderSkipped: false }],
      },
      options: {
        indexAxis: 'y', responsive: true, maintainAspectRatio: false,
        plugins: { legend: { display: false }, tooltip: { callbacks: { label: c => ` ${c.raw.toFixed(2)}% relative abundance` } } },
        scales: {
          x: { ticks: { callback: v => v + '%', font: { size: 11 } }, grid: { color: 'rgba(128,128,128,0.08)' }, border: { display: false } },
          y: { ticks: { font: { size: 11, style: 'italic' }, autoSkip: false }, grid: { display: false }, border: { display: false } },
        },
      },
    })
    return () => { if (chartRef.current) chartRef.current.destroy() }
  }, [top10])
  return <div style={{ position: 'relative', width: '100%', height: Math.max(260, top10.length * 38) }}><canvas ref={canvasRef} /></div>
}

// ── Descriptive Panel ─────────────────────────────────────────────────────────

function Top10Row({ g, color, expanded }) {
  const hasFuncs = g.functions && g.functions.length > 0
  return (
    <tr style={{ borderBottom: '1px solid #F0F0F0' }}>
      <td style={{ padding: '8px 12px', whiteSpace: 'nowrap', verticalAlign: 'top' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginTop: 4 }}>
          <span style={{ width: 10, height: 10, borderRadius: 2, background: color }} />
          <em style={{ fontWeight: 500, color: '#111' }}>{g.genus}</em>
        </div>
      </td>
      <td style={{ padding: '8px 12px', verticalAlign: 'top' }}>
        <div style={{ marginTop: 4, color: '#777', fontWeight: 500, fontSize: 13 }}>{(g.abundance * 100).toFixed(2)}%</div>
      </td>
      <td style={{ padding: '8px 12px', verticalAlign: 'top' }}>
        {hasFuncs ? (
          <div>
            {!expanded && <div style={{ marginTop: 4, fontSize: 12, fontWeight: 600, color: '#938575' }}>{g.functions.length} function{g.functions.length > 1 ? 's' : ''} mapped</div>}
            {expanded && (
              <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginTop: 4 }}>
                {g.functions.map((func, idx) => {
                  const name = typeof func === 'string' ? func : func.function;
                  return (
                    <span key={idx} style={{ background: '#EAE6DF', color: '#6B5E52', padding: '3px 10px', borderRadius: 14, fontSize: 11, fontWeight: 500 }}>{name.replace(/_/g, ' ')}</span>
                  )
                })}
              </div>
            )}
          </div>
        ) : (
          <span style={{ color: '#A3A3A3', fontSize: 11, display: 'inline-block', marginTop: 4 }}>Unclassified</span>
        )}
      </td>
    </tr>
  )
}

function DescriptivePanel({ data }) {
  const divStyle = DIV_BADGE[data.diversity_status] || DIV_BADGE.Normal
  const [funcsExpanded, setFuncsExpanded] = useState(false)
  return (
    <>
      <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 20 }}>
        <MetricCard label="Shannon entropy" value={data.shannon_entropy.toFixed(3)} sub="H′ index" />
        <MetricCard label="Observed genera" value={data.observed_genera} sub={`of ${data.total_genera} total`} />
        <MetricCard label="Diversity status" value={<Badge bg={divStyle.bg} color={divStyle.color}>{data.diversity_status}</Badge>} sub={{ Low: "H′ < 1.5", Normal: "1.5 ≤ H′ < 2.8", High: "H′ ≥ 2.8" }[data.diversity_status]} />
        <MetricCard label="Dominant genus" value={<span style={{ fontSize: 15, fontStyle: 'italic' }}>{data.dominant_genus || '—'}</span>} sub={data.dominant_genus ? `${(data.dominant_abundance * 100).toFixed(1)}% rel. abund.` : ''} />
      </div>
      <div style={{ background: '#fff', border: '0.5px solid #E8E4DC', borderRadius: 12, padding: '1rem 1.25rem' }}>
        <div style={{ fontSize: 11, fontWeight: 600, color: '#938575', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 16 }}>Top 10 genera — relative abundance</div>
        <div style={{ marginBottom: 24 }}><GenusBarChart top10={data.top10} /></div>
        <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: 20 }}>
          <thead>
            <tr style={{ background: '#F9F9F9', borderBottom: '1px solid #E8E8E8' }}>
              <th style={{ padding: '8px 12px', textAlign: 'left', fontWeight: 600, color: '#666', fontSize: 11, textTransform: 'uppercase' }}>Genus</th>
              <th style={{ padding: '8px 12px', textAlign: 'left', fontWeight: 600, color: '#666', fontSize: 11, textTransform: 'uppercase' }}>Relative Abundance</th>
              <th style={{ padding: '8px 12px', textAlign: 'left' }}>
                <button onClick={() => setFuncsExpanded(!funcsExpanded)} style={{ background: 'none', border: 'none', padding: 0, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6, fontSize: 11, fontWeight: 600, color: '#666', textTransform: 'uppercase', outline: 'none' }}>
                  Mapped Functions (FAPROTAX)
                  <span style={{ transform: funcsExpanded ? 'rotate(180deg)' : 'none', transition: 'transform 0.2s', fontSize: 9 }}>▼</span>
                </button>
              </th>
            </tr>
          </thead>
          <tbody>
            {data.top10.map((g, i) => <Top10Row key={g.genus} g={g} color={COLORS[i % COLORS.length]} expanded={funcsExpanded} />)}
          </tbody>
        </table>
      </div>
    </>
  )
}

// ── Diagnostic Panel ──────────────────────────────────────────────────────────

function DiagnosticPanel({ data }) {
  const stress = STRESS_BADGE[data.stress_level] || STRESS_BADGE[0]
  const pct_val = ((data.stress_level / 3) * 100).toFixed(1)
  return (
    <>
      <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 20 }}>
        <MetricCard label="Stress classification" value={<Badge bg={stress.bg} color={stress.color}>{stress.label}</Badge>} />
        <MetricCard label="Flags triggered" value={data.flags.length} sub={`${data.critical_count} critical · ${data.warning_count} warning`} />
        <MetricCard label="Critical genera"
          value={
            data.flags.filter(f => f.severity === 'critical').length > 0
              ? <span style={{ fontSize: 13, fontStyle: 'italic', lineHeight: 1.4 }}>{data.flags.filter(f => f.severity === 'critical').map(f => f.genus).join(', ')}</span>
              : '—'
          }
        />
        {data.confidence && (
          <MetricCard
            label="Confidence level"
            value={<Badge bg={CONF_STYLE[data.confidence.level]?.dot + '22'} color={CONF_STYLE[data.confidence.level]?.text}>{data.confidence.level}</Badge>}
            sub={`Composite accuracy: ${Math.round(data.confidence.score * 100)}%`}
          />
        )}
      </div>

      {/* Disturbance continuum */}
      <div style={{ background: '#fff', border: '0.5px solid #E8E4DC', borderRadius: 12, padding: '1rem 1.25rem', marginBottom: 16 }}>
        <div style={{ fontSize: 11, fontWeight: 600, color: '#938575', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 12 }}>Disturbance continuum</div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 8 }}>
          <span style={{ fontSize: 11, color: '#938575', whiteSpace: 'nowrap' }}>Stable</span>
          <div style={{ flex: 1, position: 'relative', height: 8, borderRadius: 4, background: 'linear-gradient(to right,#1D9E75,#BA7517,#E24B4A)' }}>
            <div style={{ position: 'absolute', left: `calc(${pct_val}% - 1px)`, top: -4, width: 2, height: 16, background: '#222', borderRadius: 1 }} />
          </div>
          <span style={{ fontSize: 11, color: '#938575', whiteSpace: 'nowrap' }}>Heavily Disturbed</span>
        </div>
        <div style={{ fontSize: 13, color: '#938575' }}>Current: <strong style={{ color: '#111' }}>{stress.label}</strong></div>
      </div>

      {/* Flags */}
      <div style={{ background: '#fff', border: '0.5px solid #E8E4DC', borderRadius: 12, padding: '1rem 1.25rem' }}>
        <div style={{ fontSize: 11, fontWeight: 600, color: '#938575', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 12 }}>Flagged genera — detailed breakdown</div>
        {data.flags.length === 0
          ? <p style={{ fontSize: 13, color: '#938575', textAlign: 'center', padding: '1rem 0' }}>No ecological stress flags triggered. Community appears within expected bounds.</p>
          : <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {data.flags.map((f, i) => {
                const sevStyle = SEV_BADGE[f.severity] || SEV_BADGE.info
                const bgStyle  = FLAG_BG[f.severity]  || FLAG_BG.info
                return (
                  <div key={i} style={{ borderRadius: 8, padding: '12px 14px', ...bgStyle }}>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 8, marginBottom: 6 }}>
                      <span style={{ fontSize: 14, fontWeight: 600, fontStyle: 'italic', color: '#111' }}>{f.genus}</span>
                      <span style={{ fontSize: 11, fontWeight: 600, padding: '2px 8px', borderRadius: 4, ...sevStyle }}>{f.severity.toUpperCase()}</span>
                    </div>
                    <div style={{ fontSize: 12, color: '#6B5E52', marginBottom: 4 }}>
                      Abundance: <strong>{(f.abundance * 100).toFixed(2)}%</strong>
                      &nbsp;|&nbsp; Threshold: {f.threshold}
                      &nbsp;|&nbsp; {f.direction}
                    </div>
                    <div style={{ fontSize: 13, lineHeight: 1.55, color: '#333' }}>{f.interpretation}</div>
                    {f.functions && f.functions.length > 0 && (
                      <div style={{ marginTop: 10, display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                        <span style={{ fontSize: 11, fontWeight: 600, color: '#938575', textTransform: 'uppercase', marginRight: 4, display: 'flex', alignItems: 'center' }}>Bio-functions:</span>
                        {f.functions.map((func, idx) => {
                          const name = typeof func === 'string' ? func : func.function;
                          return (
                            <span key={idx} style={{ background: '#EAE6DF', color: '#6B5E52', padding: '2px 8px', borderRadius: 12, fontSize: 11, fontWeight: 500 }}>{name.replace(/_/g, ' ')}</span>
                          )
                        })}
                      </div>
                    )}
                  </div>
                )
              })}
            </div>
        }
      </div>
    </>
  )
}

// ── Predictive Panel Sub-components ──────────────────────────────────────────

function CyclingRiskCard({ title, index, risk, ratioLabel, prod, ox, prodLabel, oxLabel, signalSufficient, thresholds }) {
  const riskStyle = RISK_COLORS[risk] || RISK_COLORS.Low
  const maxIdx = thresholds ? thresholds[2] * 1.5 : 10
  const barPct  = Math.min((index / maxIdx) * 100, 100)

  return (
    <div style={{ flex: 1, minWidth: 220, background: '#fff', border: `1.5px solid ${riskStyle.bar}22`, borderRadius: 12, padding: '1rem 1.25rem' }}>
      <div style={{ fontSize: 11, fontWeight: 700, color: '#938575', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 10 }}>{title}</div>

      {/* Risk badge + index value */}
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, marginBottom: 10 }}>
        <span style={{ fontSize: 28, fontWeight: 700, color: riskStyle.bar, lineHeight: 1 }}>{index.toFixed(2)}</span>
        <Badge bg={riskStyle.bg} color={riskStyle.color}>{risk}</Badge>
      </div>

      {/* Ratio bar */}
      <div style={{ height: 6, background: '#F0EDE8', borderRadius: 3, marginBottom: 8 }}>
        <div style={{ width: `${barPct}%`, height: '100%', borderRadius: 3, background: riskStyle.bar, transition: 'width 0.6s ease' }} />
      </div>

      <div style={{ fontSize: 12, color: '#555', marginBottom: 8, fontStyle: 'italic' }}>{ratioLabel}</div>

      {/* Production vs Oxidation row */}
      <div style={{ display: 'flex', gap: 12, fontSize: 11, color: '#777', marginBottom: !signalSufficient ? 8 : 0 }}>
        <span>↑ {prodLabel}: <strong style={{ color: '#333' }}>{(prod * 100).toFixed(3)}%</strong></span>
        <span>↓ {oxLabel}: <strong style={{ color: '#333' }}>{(ox * 100).toFixed(3)}%</strong></span>
      </div>

      {/* Insufficient signal warning */}
      {!signalSufficient && (
        <div style={{ marginTop: 8, padding: '6px 10px', background: '#FAEEDA', borderRadius: 6, fontSize: 11, color: '#7A4700' }}>
          ⚠ Low confidence — insufficient opposing pathway signal. Interpret with caution.
        </div>
      )}

      {/* Threshold reference */}
      {thresholds && thresholds.length === 3 && (
        <div style={{ marginTop: 10, display: 'flex', gap: 6, flexWrap: 'wrap' }}>
          <span style={{ fontSize: 10, color: '#938575' }}>Dataset quartiles:</span>
          {['Q1', 'Q2', 'Q3'].map((q, i) => (
            <span key={q} style={{ fontSize: 10, color: '#938575' }}>{q}={thresholds[i].toFixed(2)}</span>
          ))}
        </div>
      )}
    </div>
  )
}

function AnoxicSupportCard({ asi, asiLevel }) {
  const levelStyle = { Minor: { bg: '#E1F5EE', color: '#085041' }, Moderate: { bg: '#FAEEDA', color: '#7A4700' }, Pervasive: { bg: '#FCEBEB', color: '#501313' } }
  const s = levelStyle[asiLevel] || levelStyle.Minor
  return (
    <div style={{ flex: 1, minWidth: 160, background: '#fff', border: '0.5px solid #E8E4DC', borderRadius: 12, padding: '1rem 1.25rem' }}>
      <div style={{ fontSize: 11, fontWeight: 700, color: '#938575', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 10 }}>Anoxic Support Index</div>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, marginBottom: 8 }}>
        <span style={{ fontSize: 28, fontWeight: 700, color: '#555', lineHeight: 1 }}>{asi.toFixed(4)}</span>
        <Badge bg={s.bg} color={s.color}>{asiLevel}</Badge>
      </div>
      <div style={{ fontSize: 11, color: '#777', lineHeight: 1.5 }}>
        Dark H₂ oxidation + Iron respiration + Fumarate respiration.<br />
        Contextual indicator of pervasive anoxic microenvironments.
      </div>
    </div>
  )
}

function TrajectoryModule({ trajectory }) {
  if (!trajectory) return null

  const dirIcon = { 'Escalating Risk': '↗', 'Stable': '→', 'Declining Risk': '↘' }[trajectory.direction] || '→'
  const dirColor = { 'Escalating Risk': '#D85A30', 'Stable': '#BA7517', 'Declining Risk': '#1D9E75' }[trajectory.direction] || '#BA7517'
  const [showAssumptions, setShowAssumptions] = useState(false)

  return (
    <div style={{ background: '#fff', border: '0.5px solid #E8E4DC', borderRadius: 12, padding: '1.25rem 1.5rem', marginBottom: 16 }}>
      <div style={{ fontSize: 11, fontWeight: 700, color: '#938575', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 14 }}>
        Functional Risk Trajectory — Cross-Sample Analysis
      </div>

      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 14 }}>
        <span style={{ fontSize: 42, color: dirColor, lineHeight: 1, fontWeight: 300 }}>{dirIcon}</span>
        <div>
          <div style={{ fontSize: 18, fontWeight: 700, color: dirColor, marginBottom: 4 }}>{trajectory.direction}</div>
          <div style={{ fontSize: 12, color: '#777' }}>
            {trajectory.sample_count} sample{trajectory.sample_count !== 1 ? 's' : ''} · slope = {trajectory.slope.toFixed(4)} · <ConfidenceBadge confidence={{ level: trajectory.confidence }} />
          </div>
        </div>
      </div>

      <div style={{ fontSize: 13, lineHeight: 1.65, color: '#333', marginBottom: 14, padding: '10px 14px', background: '#F8F7F4', borderRadius: 8 }}>
        {trajectory.projected_risk_state}
      </div>

      <button
        onClick={() => setShowAssumptions(!showAssumptions)}
        style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: 12, color: '#938575', display: 'flex', alignItems: 'center', gap: 6, padding: 0 }}
      >
        <span style={{ transform: showAssumptions ? 'rotate(180deg)' : 'none', transition: 'transform 0.2s', fontSize: 9 }}>▼</span>
        Modeling assumptions ({trajectory.assumptions.length})
      </button>
      {showAssumptions && (
        <ul style={{ margin: '10px 0 0', padding: '0 0 0 18px', listStyle: 'disc' }}>
          {trajectory.assumptions.map((a, i) => (
            <li key={i} style={{ fontSize: 12, color: '#777', lineHeight: 1.55, marginBottom: 4 }}>{a}</li>
          ))}
        </ul>
      )}
    </div>
  )
}

function ManagementActionCard({ rec }) {
  const pStyle = PRIORITY_STYLE[rec.priority] || PRIORITY_STYLE['P3 — Monitor']
  const [expanded, setExpanded] = useState(false)

  return (
    <div style={{ borderRadius: 10, border: `1.5px solid ${pStyle.border}30`, background: pStyle.bg, padding: '1rem 1.25rem', marginBottom: 12 }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', flexWrap: 'wrap', gap: 8, marginBottom: 8 }}>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
          <Badge bg={pStyle.badge.bg} color={pStyle.badge.color}>{rec.priority}</Badge>
          <span style={{ fontSize: 12, fontWeight: 600, color: '#555' }}>{rec.pathway}</span>
        </div>
        <span style={{ fontSize: 11, color: '#938575', fontFamily: 'var(--mono, monospace)', whiteSpace: 'nowrap' }}>{rec.trigger_index}</span>
      </div>

      <div style={{ fontSize: 13, fontWeight: 600, color: '#222', marginBottom: 6 }}>Observation</div>
      <div style={{ fontSize: 13, color: '#444', lineHeight: 1.6, marginBottom: 12 }}>{rec.observation}</div>

      <div style={{ fontSize: 13, fontWeight: 600, color: '#222', marginBottom: 6 }}>Scientific Rationale</div>
      <div style={{ fontSize: 13, color: '#666', lineHeight: 1.6, marginBottom: 10 }}>{rec.rationale}</div>

      <button onClick={() => setExpanded(!expanded)} style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: 11, color: '#938575', display: 'flex', alignItems: 'center', gap: 6, padding: 0, marginBottom: expanded ? 8 : 0 }}>
        <span style={{ transform: expanded ? 'rotate(180deg)' : 'none', transition: 'transform 0.2s', fontSize: 9 }}>▼</span>
        Recommended Action
      </button>

      {expanded && (
        <div style={{ fontSize: 12, color: '#333', lineHeight: 1.6, padding: '10px 12px', background: '#fff', borderRadius: 6, border: '0.5px solid #E8E4DC', marginBottom: 8 }}>
          {rec.action}
        </div>
      )}

      <div style={{ fontSize: 11, color: '#938575', borderTop: '0.5px solid #E8E4DC', paddingTop: 8 }}>{rec.confidence_note}</div>
    </div>
  )
}

function ConfidenceBreakdownCard({ confidence }) {
  if (!confidence) return null
  const w = confidence.weights || {}
  const items = [
    { label: 'FAPROTAX functional coverage', value: confidence.functional_coverage, weight: w.coverage || 0.40 },
    { label: 'Shannon diversity (H\' / 5.0)', value: confidence.diversity_component, weight: w.diversity || 0.20 },
    { label: 'Sequencing depth (reads)', value: confidence.depth_component, weight: w.depth || 0.20 },
    { label: 'Cross-sample consistency', value: confidence.cross_sample_consistency, weight: w.consistency || 0.20 },
  ]
  return (
    <div style={{ background: '#fff', border: '0.5px solid #E8E4DC', borderRadius: 12, padding: '1rem 1.25rem', marginBottom: 16 }}>
      <div style={{ fontSize: 11, fontWeight: 700, color: '#938575', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 14 }}>
        Confidence Score Breakdown
      </div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        {items.map(item => (
          <div key={item.label}>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, color: '#555', marginBottom: 4 }}>
              <span>{item.label}</span>
              <span style={{ color: '#111', fontWeight: 600 }}>{(item.value * 100).toFixed(0)}% <span style={{ color: '#938575', fontWeight: 400 }}>× {(item.weight * 100).toFixed(0)}%</span></span>
            </div>
            <div style={{ height: 5, background: '#F0EDE8', borderRadius: 3 }}>
              <div style={{ width: `${item.value * 100}%`, height: '100%', background: '#1D9E75', borderRadius: 3, transition: 'width 0.4s' }} />
            </div>
          </div>
        ))}
      </div>
      {confidence.caveats && confidence.caveats.length > 0 && (
        <div style={{ marginTop: 14 }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: '#938575', textTransform: 'uppercase', marginBottom: 6 }}>Caveats</div>
          {confidence.caveats.map((c, i) => (
            <div key={i} style={{ fontSize: 12, color: '#7A4700', background: '#FAEEDA', borderRadius: 6, padding: '6px 10px', marginBottom: 6 }}>{c}</div>
          ))}
        </div>
      )}
    </div>
  )
}

function PredictivePanel({ data }) {
  const indices = data.cycling_indices
  const confidence = data.confidence
  const trajectory = data.trajectory
  const recs = data.recommendations || []

  const methodologyNote = (
    <div style={{ fontSize: 11, color: '#938575', background: '#F8F7F4', borderRadius: 8, padding: '8px 12px', marginBottom: 16, lineHeight: 1.6 }}>
      <strong>Methodology note:</strong> Functional inference is based on FAPROTAX literature assignments.
      Results represent ecological functional potential, not confirmed metabolic activity.
      Indices are calibrated to dataset-relative percentile quartiles. Field validation is recommended for P1-level recommendations.
    </div>
  )

  if (!indices) {
    return (
      <div style={{ padding: '2rem', textAlign: 'center', color: '#938575', fontSize: 13 }}>
        {methodologyNote}
        Risk Projection indices not available for this sample. Ensure FAPROTAX database is loaded and genera are mapped.
      </div>
    )
  }

  return (
    <>
      {methodologyNote}

      {/* Trajectory */}
      <TrajectoryModule trajectory={trajectory} />

      {/* Cycling Risk Gauges */}
      <div style={{ fontSize: 11, fontWeight: 700, color: '#938575', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 10 }}>
        Biogeochemical Cycling Risk — Pathway Indices
      </div>
      <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 16 }}>
        <CyclingRiskCard
          title="Methane Cycle Index (MCI)"
          index={indices.mci}
          risk={indices.mci_risk}
          ratioLabel={indices.ch4_ratio_label}
          prod={indices.ch4_prod_raw}
          ox={indices.ch4_ox_raw}
          prodLabel="CH₄ Production"
          oxLabel="Methanotrophy"
          signalSufficient={indices.mci_signal_sufficient}
          thresholds={indices.mci_thresholds}
        />
        <CyclingRiskCard
          title="Sulfur Cycle Index (SCI)"
          index={indices.sci}
          risk={indices.sci_risk}
          ratioLabel={indices.s_ratio_label}
          prod={indices.s_red_raw}
          ox={indices.s_ox_raw}
          prodLabel="S Reduction"
          oxLabel="S Oxidation"
          signalSufficient={indices.sci_signal_sufficient}
          thresholds={indices.sci_thresholds}
        />
        <AnoxicSupportCard asi={indices.asi} asiLevel={indices.asi_level} />
      </div>

      {/* Confidence breakdown */}
      <ConfidenceBreakdownCard confidence={confidence} />

      {/* Management action cards */}
      {recs.length > 0 && (
        <>
          <div style={{ fontSize: 11, fontWeight: 700, color: '#938575', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 12 }}>
            Index-Driven Management Recommendations
          </div>
          {recs.map((rec, i) => <ManagementActionCard key={i} rec={rec} />)}
        </>
      )}

      {recs.length === 0 && (
        <div style={{ textAlign: 'center', padding: '2rem', color: '#938575', fontSize: 13 }}>
          No management actions triggered at current index levels. Continue routine monitoring.
        </div>
      )}
    </>
  )
}

// ══════════════════════════════════════════════════════════════════════════════
// MAIN EMBEDDED COMPONENT
// ══════════════════════════════════════════════════════════════════════════════

function FilterAuditTooltip({ audit }) {
  const [show, setShow] = useState(false);
  if (!audit || audit.samples_dropped === 0) return null;

  return (
    <div style={{ position: 'relative', display: 'inline-block', zIndex: show ? 100 : 1 }} 
         onMouseEnter={() => setShow(true)} 
         onMouseLeave={() => setShow(false)}>
      <div style={{ 
        display: 'flex', alignItems: 'center', gap: 5, cursor: 'help', 
        padding: '5px 12px', borderRadius: 20, 
        background: show ? '#EAE6DF' : '#F8F7F4', 
        border: '0.5px solid #E0DCD4', 
        color: show ? '#6B5E52' : '#938575', 
        fontSize: 12, fontWeight: 600, transition: 'all 0.2s ease' 
      }}>
        <span style={{ fontSize: 13, transform: 'translateY(-0.5px)' }}>ⓘ</span>
        <span>{audit.samples_retained} / {audit.samples_submitted} Samples Validated</span>
      </div>
      
      {show && (
        <div style={{
          position: 'absolute', top: 'calc(100% + 8px)', right: 0,
          background: '#fff', border: '0.5px solid #E8E4DC', borderRadius: 10, padding: '14px 16px',
          width: 340, boxShadow: '0 12px 40px rgba(0,0,0,0.12)', zIndex: 100,
          textAlign: 'left'
        }}>
          <div style={{ fontSize: 10.5, fontWeight: 700, color: '#A0988A', marginBottom: 8, textTransform: 'uppercase', letterSpacing: '0.04em' }}>
            Technical Note · Cohort Refinement
          </div>
          <div style={{ fontSize: 12.5, color: '#333', lineHeight: 1.5, marginBottom: 12 }}>
            <strong>{audit.samples_dropped} sample{audit.samples_dropped > 1 ? 's' : ''}</strong> currently suppressed from the reporting module due to rigorous statistical quality restrictions:
          </div>
          <ul style={{ paddingLeft: 18, margin: 0, fontSize: 12, color: '#666', display: 'flex', flexDirection: 'column', gap: 8, lineHeight: 1.45 }}>
            {audit.low_depth_samples_removed?.length > 0 && (
              <li>Insufficient sequencing depth (&lt;{audit.min_depth_threshold_used} reads): <br/><i style={{color:'#888'}}>{audit.low_depth_samples_removed.join(', ')}</i></li>
            )}
            {audit.empty_after_filter_samples?.length > 0 && (
              <li>Consolidated as noise (zero post-filter variance): <br/><i style={{color:'#888'}}>{audit.empty_after_filter_samples.join(', ')}</i></li>
            )}
            {audit.zero_genus_abundance_samples?.length > 0 && (
              <li>No resolved taxonomic biomarker signal: <br/><i style={{color:'#888'}}>{audit.zero_genus_abundance_samples.join(', ')}</i></li>
            )}
          </ul>
        </div>
      )}
    </div>
  )
}

export function AnalysisEmbedded({ jobId, initialTab = 'descriptive' }) {
  const [report, setReport]   = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError]     = useState(null)
  const [tab, setTab]         = useState(initialTab)
  const [descIdx, setDescIdx] = useState(0)
  const [diagIdx, setDiagIdx] = useState(0)
  const [predIdx, setPredIdx] = useState(0)
  const [showExport, setShowExport] = useState(false)

  useEffect(() => {
    if (!jobId) return
    setLoading(true)
    setError(null)
    ingestApi.reportGenerate(jobId)
      .then(res => setReport(res.data))
      .catch(err => setError(err.response?.data?.detail || err.message || 'Unknown error'))
      .finally(() => setLoading(false))
  }, [jobId])

  if (!jobId) return null

  const TABS = ['descriptive', 'diagnostic', 'predictive']
  const TAB_LABELS = { descriptive: 'Descriptive', diagnostic: 'Diagnostic', predictive: 'Risk Projection' }

  return (
    <div style={{ marginTop: 24 }}>
      {error && (
        <div style={{ background: '#FCEBEB', border: '0.5px solid #E24B4A', borderRadius: 8, padding: '12px 16px', color: '#501313', fontSize: 13, marginBottom: 16 }}>
          Analysis failed: {error}
        </div>
      )}

      {loading && (
        <div style={{ textAlign: 'center', padding: '3rem', color: '#938575', fontSize: 14 }}>
          <div style={{ marginBottom: 12 }}><span className="spinner" style={{ display: 'inline-block' }} /></div>
          Generating report from your dataset…
        </div>
      )}

      {report && !loading && (
        <>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12, marginBottom: 20 }}>
            <div style={{ display: 'flex', gap: 4, background: '#F8F7F4', borderRadius: 8, padding: 3 }}>
              {TABS.map(t => (
                <button
                  key={t}
                  onClick={() => setTab(t)}
                  style={{
                    padding: '6px 14px', fontSize: 13,
                    border: tab === t ? '0.5px solid #E8E4DC' : 'none',
                    borderRadius: 6, cursor: 'pointer',
                    background: tab === t ? '#fff' : 'transparent',
                    color: tab === t ? '#111' : '#938575',
                    fontFamily: 'Instrument Sans', fontWeight: tab === t ? 600 : 400,
                  }}
                >
                  {TAB_LABELS[t] || t}
                </button>
              ))}
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
              <FilterAuditTooltip audit={report.sample_filter_audit} />
              <button
                id="export-pdf-btn"
                className="btn btn-ghost hide-print"
                style={{ fontSize: 13, padding: '7px 16px', background: '#F9F9F9', display: 'flex', alignItems: 'center', gap: 6 }}
                onClick={() => setShowExport(true)}
              >
                ↓ Export PDF
              </button>
            </div>
          </div>

          {tab === 'descriptive' && report.descriptive?.length > 0 && (
            <>
              <SampleChips samples={report.descriptive} active={descIdx} onSelect={setDescIdx} />
              <DescriptivePanel data={report.descriptive[descIdx]} />
            </>
          )}

          {tab === 'diagnostic' && report.diagnostic?.length > 0 && (
            <>
              <SampleChips samples={report.diagnostic} active={diagIdx} onSelect={setDiagIdx} />
              <DiagnosticPanel data={report.diagnostic[diagIdx]} />
            </>
          )}

          {tab === 'predictive' && report.diagnostic?.length > 0 && (
            <>
              <SampleChips samples={report.diagnostic} active={predIdx} onSelect={setPredIdx} />
              <PredictivePanel data={report.diagnostic[predIdx]} />
            </>
          )}
        </>
      )}

      {showExport && report && (
        <ExportModal report={report} onClose={() => setShowExport(false)} />
      )}
    </div>
  )
}

// ══════════════════════════════════════════════════════════════════════════════
// STANDALONE PAGE
// ══════════════════════════════════════════════════════════════════════════════

export default function AnalysisReportPage() {
  const { jobId }  = useParams()
  const location   = useLocation()
  const navigate   = useNavigate()
  const initialTab = location.state?.tab ?? 'descriptive'

  if (!jobId) {
    return (
      <>
        <div className="page-header">
          <h2 style={{ fontWeight: 600 }}>Analysis Reports</h2>
          <p>Descriptive · Diagnostic · Risk Projection — pathway-indexed DSS engine</p>
          <hr className="divider" />
        </div>
        <div className="card" style={{ textAlign: 'center', padding: '3rem', color: '#938575' }}>
          <p style={{ fontSize: 14 }}>No job ID provided. Navigate here from the Ingested Data page.</p>
          <button className="btn btn-ghost" style={{ marginTop: 16 }} onClick={() => navigate('/ingested-data')}>
            ← Go to Ingested Files
          </button>
        </div>
      </>
    )
  }

  return (
    <>
      <div className="page-header" style={{ position: 'relative' }}>
        <button onClick={() => navigate(-1)} className="btn-ghost"
          style={{ position: 'absolute', right: 0, top: 4, padding: '6px 14px', fontSize: 13, fontFamily: 'Instrument Sans', fontWeight: 600, border: 'none', background: 'transparent', color: '#938575' }}>
          ← Back
        </button>
        <h2 style={{ fontWeight: 600 }}>Analysis Reports</h2>
        <p>Descriptive · Diagnostic · Risk Projection — pathway-indexed DSS engine</p>
        <hr className="divider" />
      </div>
      <AnalysisEmbedded jobId={jobId} initialTab={initialTab} />
    </>
  )
}
